info:
  version: 1.0.5
  description: N3IWF initial local configuration

configuration:
  n3iwfInformation:
    globalN3IWFID: # ID used to globally identify an N3IWF
      plmnID: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
        mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      n3iwfID: 135 # ID used to identify an N3IWF in PLMN (uinteger, range: 0~65535)
    name: free5GC_N3IWF # The name of this N3IWF
    supportedTAList: # Tracking Area supported by this N3IWF
      - tac: 000001 # Tracking Area Code (3 bytes hex string, range: 000000~FFFFFF)
        broadcastPlmnList: # Refer to TS 38.413
          - plmnID: # Public Land Mobile Network ID
              mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
              mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
            taiSliceSupportList: # Network Slice supported in this TAI
              - snssai: # Single Network Slice Selection Assistance Information
                  sst: 1 # Slice/Service Type (1 byte hex string, range: 0~F)
                  sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
              - snssai: # Single Network Slice Selection Assistance Information
                  sst: 1 # Slice/Service Type (1 byte hex string, range: 0~F)
                  sd: 112233 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)

  # --- N2 Interfaces ---
  amfSCTPAddresses: # the IP list of N2 interfaces (SCTP) on AMF when using NGAP
    - ip:
        - 10.200.200.1
      port: 38412
  nasTcpPort: 20000 # TCP port which the NAS listens on

  # --- Nwu Interfaces ---
  ikeBindAddress: 192.168.127.1 # Nwu interface  IP address (IKE) on this N3IWF
  ipSecTunnelAddress: 10.0.0.1 # Tunnel IP address of XFRM interface on this N3IWF
  ueIpAddressRange: 10.0.0.0/24 # IP address pool allocated to UE in IPSec tunnel
  xfrmInterfaceName: xfrmi # Prefix of XFRM interface name created by N3IWF
  xfrmInterfaceID: 1 # XFRM interface if_id for IPSec routing (Any value except to 0, default value is 7 if not defined)

  # --- N3 Interfaces ---
  n3iwfGtpBindAddress: 10.200.200.2 # IP address of N3 interface (GTP) on this N3IWF

  fqdn: n3iwf.free5gc.org # FQDN of this N3IWF

  # --- Security ---
  privateKey: cert/n3iwf.key # Private key file path
  certificateAuthority: cert/n3iwf.pem # Certificate Authority (CA) file path
  certificate: cert/n3iwf.pem # Certificate file path

  # sending dead peer detection message
  livenessCheck:
    enable: true # true or false
    transFreq: 60s # frequency of transmission
    maxRetryTimes: 4 # the max number of DPD response of UE

logger: # log output setting
  enable: true # true or false
  level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  reportCaller: false # enable the caller report or not, value: true or false
